[build]
  publish = "."

[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"